### ISSUE TITLE
Live Item if Char offline return Char notfound

### ISSUE THREAD

**Issue by kotsh23** [JellyBitz/vSRO-ServerAddon#2]
Hello boss!

i tried to send live item to Offline char but its return with action_result 5 
i hope if you can change it Behavior to retry or trigger check when player come online and resend him

Thank you for your great work
waiting sro_client dll with awesome features <3

**Comment by JellyBitz** [comment]
I see pointless to add this detection/event to gameserver neither possible for me at the moment.

You should check or keep logs from offline/online players using the database events directly, executing the gameserver action if they are online otherwise make a query directly to add the item to his inventory.

**Comment by kotsh23** [comment]
Okey @JellyBitz <3 
thank you for your great work
